<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<?php
$style		= '';
$require	= 'required-entry ';
$cards		= $this->getPriorCards();

if( $cards && count($cards) > 0 ):
	$style		= ' style="display:none"';
	$require	= '';
	?>
	<li>
		<label for="<?php echo $_code; ?>_payment_id"><?php echo $this->__('Pay with card on file'); ?></label>
		<div class="input-box">
			<select name="payment[payment_id]" id="<?php echo $_code; ?>_payment_id" class="<?php echo $_code; ?>_require required-entry">
				<option value=""><?php echo $this->__('-- Select One --'); ?></option>
				<?php foreach( $cards as $card ): ?>
					<option value="<?php echo $card->getId(); ?>"><?php echo $card->getFormattedCc(); ?></option>
				<?php endforeach; ?>
			</select>
			<br /><?php echo $this->__('Or,'); ?> <a href="#" onclick="$$('.<?php echo $_code; ?>_add').each(function(e){ e.toggle(); }); $$('.<?php echo $_code; ?>_require').each(function(e){ e.toggleClassName('required-entry'); if( e.hasClassName('cvv') ){ e.toggleClassName('validate-cc-cvn'); } }); return false;"><?php echo $this->__('use a different card.'); ?></a>
		</div>
	</li>
<?php endif; ?>
	<li class="<?php echo $_code ?>_add"<?php echo $style ?>>
		<label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
		<div class="input-box">
			<select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="<?php echo $require.$_code; ?>_require">
				<option value=""><?php echo $this->__('--Please Select--')?></option>
			<?php $_ccType = $this->getInfoData('cc_type') ?>
			<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
				<option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
			<?php endforeach ?>
			</select>
		</div>
	</li>
	<li class="<?php echo $_code ?>_add"<?php echo $style ?>>
		<label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text <?php echo $require.$_code; ?>_require validate-cc-number" autocomplete="off" value="" />
		</div>
	</li>
	<li class="<?php echo $_code ?>_add"<?php echo $style ?> id="<?php echo $_code ?>_cc_type_exp_div">
		<label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
		<div class="input-box">
			<div class="v-fix">
				<select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month <?php echo $require.$_code; ?>_require">
				<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
				<?php foreach ($this->getCcMonths() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</div>
			<div class="v-fix">
				<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
				<select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year <?php echo $require.$_code; ?>_require">
				<?php foreach ($this->getCcYears() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</div>
		</div>
	</li>
	<?php echo $this->getChildHtml() ?>
	<?php if($this->hasVerification()): ?>
	<li class="<?php echo $_code ?>_add"<?php echo $style ?> id="<?php echo $_code ?>_cc_type_cvv_div">
		<label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
		<div class="input-box">
			<div class="v-fix">
				<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv <?php echo $require.$_code; ?>_require <?php if( !empty( $require ) ): ?>validate-cc-cvn<?php endif; ?>" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" autocomplete="off" value="" />
			</div>
			<a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
		</div>
	</li>
	<?php endif; ?>
	<?php
	// We need to be able to identify whether they're a guest or 'registering'...
	$quote	= Mage::getSingleton('checkout/session')->getQuote();
	$items	= array();
	if( $quote && $quote->getId() ) {
		$items	= $quote->getAllItems();
	}
	?>
	<?php if( ( !isset($items[0]) || !$items[0]->isNominal() ) && ( Mage::getSingleton('customer/session')->getCustomerId() || $quote->getCheckoutMethod() == 'register' ) ): ?>
		<li class="<?php echo $_code ?>_add"<?php echo $style ?>>
			<label>&nbsp;</label>
			<input type="checkbox" name="payment[save_card]" id="<?php echo $_code ?>_save_card" value="1" checked="checked" autocomplete="on" /> 
			<label for="<?php echo $_code ?>_save_card" style="float:none;font-weight:normal;"><?php echo $this->__('Save this credit card for next time'); ?></label>
		</li>
	<?php endif; ?>
</ul>
