<?php $cardTypes = Mage::getModel('transarmor/source_cardtypes')->toArray(); ?>

<div class="page-title title-buttons">
	<h1><?php echo $this->__('Manage My Cards') ?></h1>
</div>

<div class="col2-set addresses-list">
	<div class="col-1">
		<h2><?php echo $this->__('My Credit Cards') ?></h2>
		<ol>
			<?php $cards = $this->getCards(); ?>
			<?php if( $cards !== false && count($cards) ): ?>
				<?php foreach( $cards as $card ): ?>
				<li class="item info-box">
					<h3 class="box-title"><?php echo $card->getFormattedCc(); ?> <small style="font-weight:normal">(<?php echo $cardTypes[ $card->getType() ]; ?>)</small></h3>
					<address class="box-content" style="overflow:auto">
						<?php echo $card->getFirstname().' '.$card->getLastname() ?><br />
						<?php echo $card->getAdditionalInfo('addr1') ?><br />
						<?php echo $card->getAdditionalInfo('city') ?>, <?php echo $card->getAdditionalInfo('state') ?>, <?php echo $card->getAdditionalInfo('zip') ?><br />
						<div class="right">
							<?php if( $card->inUse == 1 ): ?>
								<abbr title="<?php echo $this->__('This card cannot be modified while associated with open orders.'); ?>"><?php echo $this->__('Card In Use'); ?></abbr>
							<?php else: ?>
								<form id="edit_<?php echo $card->getId() ?>" action="<?php echo Mage::getUrl('*/*', array('_secure' => true)) ?>" method="post">
									<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
									<input type="hidden" name="c" value="<?php echo $card->getId() ?>" />
									<button class="button" type="submit"><span><span><?php echo $this->__('Edit'); ?></span></span></button>
								</form>
								<form id="del_<?php echo $card->getId() ?>" action="<?php echo Mage::getUrl('*/*/delete', array('_secure' => true)) ?>" method="post" onsubmit="return confirm('<?php echo $this->__('Are you sure you want to delete this card? This action cannot be reversed.'); ?>');">
									<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
									<input type="hidden" name="c" value="<?php echo $card->getId() ?>" />
									<button class="button" type="submit"><span><span><?php echo $this->__('Delete'); ?></span></span></button>
								</form>
							<?php endif; ?>
						</div>
					</address>
				</li>
				<?php endforeach; ?>
			<?php else: ?>
			<li class="item"><?php echo $this->__('You have not yet saved any credit cards.') ?></li>
			<?php endif; ?>
		</ol>
	</div>
	<div class="col-2">
		<?php if( $this->isEdit() ): ?>
			<h2><?php echo $this->__('Editing Card %s', $this->getCard()->getFormattedCc() ); ?></h2>
		<?php else: ?>
			<h2><?php echo $this->__('Add A Credit Card') ?></h2>
		<?php endif; ?>
		<form action="<?php echo Mage::getUrl('*/*/create/', array('_secure' => true)) ?>" method="post" style="display:block;width:270px;" id="form-validate">
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input type="hidden" name="c" value="<?php echo $this->getCard()->getId(); ?>" />
		<ul class="form-list sp-methods">
			<?php $_code = 'authnetcim'; ?>
			<li><h4><?php echo $this->__('Cardholder Information') ?></h4></li>
			<li>
				<label for="<?php echo $_code ?>_fn" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_fn" name="payment[firstname]" class="input-text required-entry" value="<?php echo $this->getCard()->getAdditionalInfo('name1'); ?>" />
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_ln" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_ln" name="payment[lastname]" class="input-text required-entry" value="<?php echo $this->getCard()->getAdditionalInfo('name2'); ?>" />
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_addr" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_addr" name="payment[address1]" class="input-text required-entry" value="<?php echo $this->getCard()->getAdditionalInfo('addr1'); ?>" />
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_city" name="payment[city]" class="input-text required-entry" value="<?php echo $this->getCard()->getAdditionalInfo('city'); ?>" />
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_st" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
				<div class="input-box">
					<select style="" class="validate-select required-entry" title="State/Province" name="payment[state]" id="region_id" style="display: none;">
						<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
					</select>
					<script type="text/javascript">
						$('region_id').setAttribute('defaultValue', '<?php echo Mage::getModel("directory/region")->loadByName( $this->getCard()->getAdditionalInfo('state'), $this->getCard()->getAdditionalInfo('country') )->getId(); ?>');
					</script>
					<input type="text" class="input-text required-entry" title="State/Province" value="<?php echo $this->getCard()->getAdditionalInfo('state'); ?>" name="payment[region]" id="region" />
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_zip" name="payment[zip]" class="input-text required-entry" value="<?php echo $this->getCard()->getAdditionalInfo('zip'); ?>" />
				</div>
			</li>
			<li>
				<label for="<?php echo $_code ?>_country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
				<div class="input-box">
					<?php echo $this->getAddressBlock()->getCountryHtmlSelect( ($this->getCard()->getAdditionalInfo('country') ? $this->getCard()->getAdditionalInfo('country') : 'US'), 'payment[country]' ); ?>
				</div>
			</li>
			
			<li><h4><?php echo $this->__('Credit Card Information') ?></h4></li>
			<?php if( $this->isEdit() ): ?>
				<li>
					<input type="radio" name="payment[sameCard]" value="1" id="sameCard_1" onchange="if(this.checked==true){ $$('.ccInfo').each(function(e){ e.hide(); }); } else { $$('.ccInfo').each(function(e){ e.show(); }); }" checked="checked" /> <label for="sameCard_1">Continue using card <?php echo $this->getCard()->getFormattedCc(); ?></label><br />
					<input type="radio" name="payment[sameCard]" value="0" id="sameCard_0" onchange="if(this.checked==true){ $$('.ccInfo').each(function(e){ e.show(); }); } else { $$('.ccInfo').each(function(e){ e.hide(); }); }" /> <label for="sameCard_0">Change credit card details</label>
				</li>
			<?php endif; ?>
			<?php $style = ($this->isEdit()) ? 'style="display:none"' : ''; ?>
			<li class="ccInfo" <?php echo $style; ?>>
				<label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
				<div class="input-box">
					<select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]">
						<option value=""><?php echo $this->__('--Please Select--')?></option>
						<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
							<option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</li>
			<li class="ccInfo" <?php echo $style; ?>>
				<label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text" value="<?php echo $this->getCard()->getFormattedCc(); ?>" />
				</div>
			</li>
			<li id="<?php echo $_code ?>_cc_type_exp_div" class="ccInfo" <?php echo $style; ?>>
				<label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
				<div class="input-box">
					<div class="v-fix">
						<select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month">
							<option value=""><?php echo $this->__('Month') ?></option>
						<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
						<?php foreach ($this->getCcMonths() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>
					</div>
					<div class="v-fix">
						<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
						<select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year">
							<option value=""><?php echo $this->__('Year') ?></option>
						<?php foreach ($this->getCcYears() as $k=>$v): ?>
							<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
						<?php endforeach ?>
						</select>
					</div>
				</div>
			</li>
			<li id="<?php echo $_code ?>_cc_type_cvv_div" class="ccInfo" <?php echo $style; ?>>
				<label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
				<div class="input-box">
					<div class="v-fix">
						<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
					</div>
				</div>
			</li>
			<li>
				<button class="button" type="submit"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				<a href="<?php echo $this->getUrl('*/*', array('_secure' => true)); ?>">Cancel</a>
			</li>
		</ul>
		</form>
		<script type="text/javascript">
		//<![CDATA[
		    var dataForm = new VarienForm('form-validate', true);
			new RegionUpdater('country', 'region', 'region_id', <?php echo Mage::helper('directory')->getRegionJson() ?>, undefined, '<?php echo $_code ?>_zip');
		    //]]>
		</script>
	</div>
</div>
<style type="text/css">
.form-list label {
	float: none;
}
.addresses-list .col-2 li {
	padding-bottom: 3px;
}
.form-list input.input-text {
	width: 254px;
}
.form-list select {
	width: 260px;
}
.sp-methods select.month {
	margin-right: 10px;
	width: 154px;
}
.sp-methods select.year {
	width: 96px;
}
</style>
