<?php $redirectEnable = Mage::getStoreConfig('shop_redirect/redirect_settings/enable'); ?>
<?php $mainWebsiteId = Mage::getStoreConfig('shop_redirect/redirect_settings/main_website'); ?>
<?php if($redirectEnable && Mage::app()->getWebsite()->getId() == $mainWebsiteId): ?>
	<script type="text/javascript">
		jQuery(document).ready(function() {
			jQuery('button.btn-cart').each(function(){
	            var $this = jQuery(this);
	            if($this.parent() != undefined && $this.parent().prev() != undefined && $this.parent().prev().attr('href') != undefined)
	            {
	            	$this.attr('onclick', "setLocation('" + $this.parent().prev().attr('href') + "');");
	            	$this.attr('magiccartEvent', '');
	            }
	        });

	        jQuery(document).off("click", 'button.btn-cart');
		});
	</script>
<?php endif; ?>