<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
	echo $this->getDesignStyles();
	$package = Mage::getDesign()->getPackageName();
	$theme = Mage::getDesign()->getTheme('frontend');
	$is_persistent = Mage::helper('opc')->isPersistentMember();
?>
<div class="msg-group"><?php echo $this->getMessagesBlock()->getGroupedHtml(); ?></div>
<div class="ambasador-container opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<div class="navigation">
		<ul class="navigation-tab">
            <li data-content="tab-1" class="active">
                <span class="circle">1</span>
                <span class="texta"> <?php echo $this->__('Ambassador<br>Info'); ?></span>
            </li>
            <li data-content="tab-2">
                <span class="circle">2</span>
                <span class="texta"> <?php echo $this->__('Ambassador<br>Profile'); ?></span>
            </li>
            <li data-content="tab-3">
                <span class="circle">3</span>
                <span class="texta"> <?php echo $this->__('Choose Your<br>Business Kit'); ?></span>
            </li>
            <li data-content="tab-4">
                <span class="circle">4</span>
                <span class="texta"> <?php echo $this->__('Payment<br>Info'); ?></span>
            </li>
            <li data-content="tab-5">
                <span class="circle">5</span>
                <span class="texta"> <?php echo $this->__('Review &<br>Submit'); ?></span>
            </li>
        </ul>
        <div class="navigation-content">
        	<div id="tab-1" style="display: block;">
				<div>
        			<form id="opc-address-form-billing" method="post">
			        	<?php echo $this->getChildHtml('billing')?>
			        </form>
    			</div>
        		<div class="buttons-set">
	           		<button type="button" title="Next" class="button btn-next" data-curr="1" data-next="2" data-validator="validateFirst"><span><span><?php echo $this->__('Next'); ?></span></span></button>
		        </div>
    		</div>
        	<div id="tab-2">
        		<div>
        			<form id="opc-ambassador-profile" method="post">
			        	<?php echo $this->getChildHtml('profile')?>
			        </form>
        		</div>
        		<div class="buttons-set">
		        	<button type="button" title="<?php echo $this->__('Previous'); ?>" class="button btn-prev" data-curr="2" data-prev="1"><span><span><?php echo $this->__('Previous'); ?></span></span></button>
			        <button type="button" title="<?php echo $this->__('Next'); ?>" id="ambassador-next" class="button btn-next" data-curr="2" data-next="3" data-validator="validateSecond"><span><span><?php echo $this->__('Next'); ?></span></span></button>
			    </div>
        	</div>
        	<div id="tab-3">
        		<div class="starterkit-block">
					<?php echo $this->getChildHtml('starterkit') ?>
				</div>
				<div class="buttons-set">
			        <button type="button" title="<?php echo $this->__('Previous'); ?>" class="button btn-prev" data-curr="3" data-prev="2"><span><span><?php echo $this->__('Previous'); ?></span></span></button>
			        <button type="button" title="<?php echo $this->__('Next'); ?>" class="button btn-next" data-curr="3" data-next="4" data-validator="validateThird"><span><span><?php echo $this->__('Next'); ?></span></span></button>
			    </div>
        	</div>
        	<div id="tab-4">
        		<div class="payment-block">
        			<h3><?php echo $this->__('Payment Information') ?></h3>
					<?php echo $this->getChildHtml('payment') ?>
				</div>
				<?php if ($this->canShip()): ?>
					<div class="shipping_method_wrapper" class="<?php if (!Mage::helper('opc')->isShowShippingForm()):?>hidden<?php endif;?>">
	                    <input type="checkbox" id="billing_use_for_shipping_yes" <?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" class="checkbox" /><label for="billing_use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
					</div>
					<script type="text/javascript">
						jQuery(document).ready(function() {
							jQuery('#billing_use_for_shipping_yes').click(function() {
								jQuery("input[name='billing[use_for_shipping]']").click();
							})
						});
					</script>
				<?php endif; ?>
				<form id="opc-address-form-shipping" class="hidden" method="post">
		        	<?php echo $this->getChildHtml('shipping')?>
		        </form>
        		<div class="buttons-set">
			        <button type="button" title="<?php echo $this->__('Previous'); ?>" class="button btn-prev" data-curr="4" data-prev="3"><span><span><?php echo $this->__('Previous'); ?></span></span></button>
			        <button type="button" title="<?php echo $this->__('Next'); ?>" class="button btn-next" data-curr="4" data-next="5" data-validator="validateForth"><span><span><?php echo $this->__('Next'); ?></span></span></button>
			    </div>
        	</div>
        	<div id="tab-5">
        		<div id="opc-review-info1">
			    	<?php echo $this->getChildHtml('review_info1'); ?>
			  	</div>
        		<?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
		    	<div class="shipping-block hidden">
		        	<h3><?php echo $this->__('Shipping Method')?></h3>
		        	<div id="shipping-block-methods">
						<?php echo $this->getChildHtml('shipping_method'); ?>
					</div>
				</div>
				<?php endif;?>
	        	<div id="opc-review-block">
			    	<?php echo $this->_getReviewHtml()?>
			  	</div>
	        	<h5 class="grand_total"><?php echo $this->__('Grand Total')?><span><?php echo Mage::helper('opc')->getGrandTotal()?></span></h5>        		
	        	<div class="buttons-set">
			        <button type="button" title="<?php echo $this->__('Previous'); ?>" class="button btn-prev" data-curr="5" data-prev="4"><span><span><?php echo $this->__('Previous'); ?></span></span></button>
			        <div class="opc-review-actions" id="checkout-review-submit">
		      			<button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
					</div>
			    </div>  
        	</div>
        </div>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function() 
    {
        jQuery('button.btn-prev').click(function() 
        {
            jQuery(".navigation-content > div").hide();
            jQuery("#tab-" + jQuery(this).attr('data-prev')).show();
            jQuery("li[data-content=tab-" + jQuery(this).attr('data-prev') + "]").addClass('active');
            jQuery("li[data-content=tab-" + jQuery(this).attr('data-curr') + "]").removeClass('active');
        });

        jQuery('button.btn-next').click(function() 
        {
        	var validate = true;
        	if(jQuery(this).attr('data-validator') != undefined && window[jQuery(this).attr('data-validator')] != undefined)
        		validate = window[jQuery(this).attr('data-validator')]();

        	if(validate)
        	{
        		jQuery(".navigation-content > div").hide();
	            jQuery("#tab-" + jQuery(this).attr('data-next')).show();
	            jQuery(".navigation-tab li").removeClass("active");
	            jQuery("li[data-content=tab-" + jQuery(this).attr('data-next') + "]").addClass('active');
        	}
        });
    });

    function validateFirst() {
    	
    	var addressForm = new VarienForm('opc-address-form-billing');
		if (!addressForm.validator.validate()){
			return false;
		} 	

		if($j_opc('.ambasador-container').attr('data-error') != undefined && $j_opc('.ambasador-container').attr('data-error') == 'true')
		{
			$j_opc('.opc-message-container').html($j_opc('.ambasador-container').attr('data-error-message'));
			$j_opc('.opc-message-wrapper').show();
			return false;
		}

		var content_confirm_block = '<?php echo $this->getChildHtml("confirm_block"); ?>';

		jQuery.fancybox({
            type: 'inline',
            content: content_confirm_block,
            closeBtn: false, // hide close button
			closeClick: false, // prevents closing when clicking INSIDE fancybox
			cyclic: false,
			helpers: { // prevents closing when clicking OUTSIDE fancybox
    			overlay: {closeClick: false} 
			},
		    keys: { // prevents closing when press ESC button
		        close: null
		    }
        });
		return false;
    }

    function validateConfirm() { 
    	if (!jQuery("#agree_terms").is(":checked")) 
		{ 
			jQuery(".agree-error").show(); 
		} 
		else 
		{ 
			jQuery(".agree-error").hide(); 
			parent.jQuery.fancybox.close(); 
			
			jQuery(".navigation-content > div").hide(); 
			jQuery("#tab-2").show(); 
			jQuery(".navigation-tab li").removeClass("active"); 
			jQuery("li[data-content=tab-2]").addClass("active"); 
		} 
	}

    function validateSecond() {
    	var profileForm = new VarienForm('opc-ambassador-profile');
		if (!profileForm.validator.validate()) {
			return false;
		}
		return true;
    }

    function validateThird() {
		if($j_opc("#username").val().trim() == "" || !$j_opc("#confirm_website").prop('checked'))
		{
			alert('<?php echo $this->__("Please enter valid website name and accept the terms and conditions!") ?>');
			return false;
		}

		var websiteForm = new VarienForm('opc-website-form');
		if (!websiteForm.validator.validate()) {
			return false;
		}

		if($j_opc('#opc-website-form #username').hasClass('validated'))
		{
			alert('<?php echo $this->__("Please enter valid website name, website name already exist.") ?>')
			return false;
		}

		return true;
    }

    function validateForth() {
    	var paymentForm = new VarienForm('co-payment-form');
		if (!paymentForm.validator.validate()) {
			return false;
		}

		if (!$j_opc('input[name="billing[use_for_shipping]"]').prop('checked')) {
			var addressForm = new VarienForm('opc-address-form-shipping');
			if (!addressForm.validator.validate()){				
				return false;
			}
		}

		getReviewDetials();	
		getBillingDetails();
		return true;
    }
    
//]]>
</script>

<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
		IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>
</script>

<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method.');?></div>
<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<div class="opc-messages">
		<a class="close-message-wrapper"><i class="fa fa-close"></i></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>