<?php 
/**
 * Julfiker_Party extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Julfiker
 * @package        Julfiker_Party
 * @copyright      Copyright (c) 2017
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event Party_participate list template
 *
 * @category    Julfiker
 * @package     Julfiker_Party
 * @author      Ultimate Module Creator
 */
?>
<?php $_partyparticipates = $this->getPartyparticipates(); ?>
<?php if ($_partyparticipates->getSize() > 0) :?>
<div class="partyparticipate-title">
    <h2><?php echo Mage::helper('julfiker_party')->__('Party_participates') ?></h2>
</div>
<div class="partyparticipates-list-container">
    <?php foreach ($_partyparticipates as $_partyparticipate) : ?>
        <div class="partyparticipate-list-item">
            <?php echo $_partyparticipate->getStatus();?>
<br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
