<tr class="recurring-profile">
	<td>
		<h3><?php echo $this->__('Business Manage System (Dashboard)'); ?></h3>
		<p class="free">
			<?php echo $this->__('First 60 Days<br/>Free'); ?>
		</p>
		<p class="price">
			<?php echo $this->__('After 60 Days<br/><span>%s/every 3 months</span>', Mage::helper('core')->currency(39.99, true, false)); ?>
		</p>
		<p class="cancel">
			<?php echo $this->__('You may cancel it at any time. <a href="#">Click here to learn more.</a>', "#") ?>
		</p>
	</td>
	<td></td>
	<td></td>
	<td class="a-right last">
		<?php echo Mage::helper('core')->currency(0, true, false); ?>
	</td>
</tr>