<div class="entry-edit-head">
	<h4 class="icon-head head-customer-address-list">
		<?php if( $this->isEdit() ): ?>
			<?php echo $this->__('Editing Card %s', $this->getCard()->getFormattedCc() ); ?>
		<?php else: ?>
			<?php echo $this->__('Add A Credit Card') ?>
		<?php endif; ?>
	</h4>
</div>
<div class="fieldset">
	<input type="hidden" name="c" value="<?php echo $this->getCard()->getId(); ?>" />
	<?php $_code = 'transarmor'; ?>
	<h4><?php echo $this->__('Cardholder Information') ?></h4>
	<table class="form-list" cellspacing="0">
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_fn"><?php echo $this->__('First Name') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $_code ?>_fn" name="trans_payment[firstname]" class="input-text" value="<?php echo $this->getCard()->getAdditionalInfo('name1'); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_ln"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $_code ?>_ln" name="trans_payment[lastname]" class="input-text" value="<?php echo $this->getCard()->getAdditionalInfo('name2'); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_addr"><?php echo $this->__('Street Address') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $_code ?>_addr" name="trans_payment[address1]" class="input-text" value="<?php echo $this->getCard()->getAdditionalInfo('addr1'); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_city"><?php echo $this->__('City') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $_code ?>_city" name="trans_payment[city]" class="input-text" value="<?php echo $this->getCard()->getAdditionalInfo('city'); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_region_id"><?php echo $this->__('State/Province') ?> <span class="required">*</span></label></td>
			<td class="value">
				<select title="State/Province" name="trans_payment[state]" id="<?php echo $_code ?>_region_id">
					<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				</select>
				<script type="text/javascript">
					$('<?php echo $_code ?>_region_id').setAttribute('defaultValue', '<?php echo Mage::getModel("directory/region")->loadByName( $this->getCard()->getAdditionalInfo('state'), $this->getCard()->getAdditionalInfo('state') )->getId(); ?>');
				</script>
				<input type="text" class="input-text" title="State/Province" value="<?php echo $this->getCard()->getAdditionalInfo('state'); ?>" name="payment[region]" id="<?php echo $_code ?>_region" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_zip"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $_code ?>_zip" name="trans_payment[zip]" class="input-text" value="<?php echo $this->getCard()->getAdditionalInfo('zip'); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_country"><?php echo $this->__('Country') ?> <span class="required">*</span></label></td>
			<td class="value">
				<?php echo $this->getAddressBlock()->getCountryHtmlSelect( ($this->getCard()->getAdditionalInfo('country') ? $this->getCard()->getAdditionalInfo('country') : 'US'), 'trans_payment[country]', $_code.'_country' ); ?>
			</td>
		</tr>
	</table>
		
	<h4><?php echo $this->__('Credit Card Information') ?></h4>
	<?php if( $this->isEdit() ): ?>
		<div>
			<input type="radio" name="trans_payment[sameCard]" value="1" id="sameCard_1" onchange="if(this.checked==true){ $('trans_CcInfo').hide(); } else { $('trans_CcInfo').show(); }" checked="checked" /> <label for="sameCard_1">Continue using card <?php echo $this->getCard()->getFormattedCc(); ?></label><br />
			<input type="radio" name="trans_payment[sameCard]" value="0" id="sameCard_0" onchange="if(this.checked==true){ $('trans_CcInfo').show(); } else { $('trans_CcInfo').hide(); }" /> <label for="sameCard_0">Change credit card details</label>
		</div>
	<?php endif; ?>
	<table class="form-list" cellspacing="0" <?php if( $this->isEdit() ): ?>style="display:none"<?php endif; ?> id="trans_CcInfo">
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label></td>
			<td class="value">
				<select id="<?php echo $_code ?>_cc_type" name="trans_payment[cc_type]">
					<option value=""><?php echo $this->__('--Please Select--')?></option>
					<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
						<option value="<?php echo $_typeCode ?>" <?php if( $_typeCode == $this->getCard()->getType() ): ?>selected="selected"<?php endif; ?>><?php echo $_typeName ?></option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $_code ?>_cc_number" name="trans_payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text <?php if( $this->getCard()->getFormattedCc() == ''): ?>validate-cc-number<?php endif; ?>" value="<?php echo $this->getCard()->getFormattedCc(); ?>" autocomplete="off" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label></td>
			<td class="value">
				<select id="<?php echo $_code ?>_expiration" name="trans_payment[cc_exp_month]" class="month" style="width:150px">
					<option value=""><?php echo $this->__('Month') ?></option>
				<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
				<?php foreach ($this->getCcMonths() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select> 
				
				<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
				<select id="<?php echo $_code ?>_expiration_yr" name="trans_payment[cc_exp_year]" class="year" style="width:80px">
					<option value=""><?php echo $this->__('Year') ?></option>
				<?php foreach ($this->getCcYears() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv" id="<?php echo $_code ?>_cc_cid" name="trans_payment[cc_cid]" value="" style="width:50px" autocomplete="off" />
			</td>
		</tr>
	</table>
	
	<table class="form-list" cellspacing="0">
		<tr>
			<td class="label"></td>
			<td class="value">
				<button class="button" type="button" onclick="transSaveCard()"><span><span><?php echo $this->__('Save') ?></span></span></button>
				<a href="#" onclick="transEditCard(0); return false;"><?php echo $this->__('Cancel'); ?></a>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript">
//<![CDATA[
	new RegionUpdater('<?php echo $_code ?>_country', '<?php echo $_code ?>_region', '<?php echo $_code ?>_region_id', <?php echo Mage::helper('directory')->getRegionJson() ?>, undefined, '<?php echo $_code ?>_zip');
	
	/* Prevent the region from holding up submit... unfortunately no better way to do this. */
	document.observe("dom:loaded", function() {
		$('<?php echo $_code ?>_region_id').removeClassName('required-entry').removeClassName('validate-select');$('<?php echo $_code ?>_region').removeClassName('required-entry');
		setInterval( "$('<?php echo $_code ?>_region_id').removeClassName('required-entry').removeClassName('validate-select');$('<?php echo $_code ?>_region').removeClassName('required-entry');", 10000 );
	});
//]]>
</script>
