<div class="col-sm-12">
    <div class="row">
        <div class="col-sm-6">
            <div style="border-style: double; height: 400px; border-color: #ec008b; border-radius: 5px">
                <!-- title -->
                <div style="font-size:24px; padding: 20px; text-align: center">You are invited to..</div>
                <!--  event info -->
                <div style="padding-top: 20px; text-align: center">
                    <h1 style="font-size: 24px; color: #ec008b">Test's Sip and Shop event</h1>
                    <div style="font-size: 18px;"> Thursday, August 2017 </div>
                    <div style="color: #8b8b8b;">
                        Start date: Jul/12,17 Start time: 10:00 AM <br />
                        End date: Jul/12,17 End time: 01:00 PM
                    </div>
                    <div style="padding: 20px 0px; text-align: center">
                        <div style="font-size:18px; color:#ec008b">Morise hours</div>
                        <div style="color: #8b8b8b;">Address....</div>
                    </div>

                    <div style="text-align: center">
                        <h2 style="font-size: 18px;"> Hosted By - Dany</h2>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-sm-6">
            <!-- Host message -->
            <div style="background: #eee">
                <div style="padding: 20px 0px; text-align: center">
                    <h1 style="font-size: 18px;">A Message From Your Host</h1>
                    <div style="color:#8b8b8b;">
                        Enjoy an evening on wine and cheese and experience <br />
                        They joy of the shopping... <br />
                        Thank you - Dany
                    </div>
                </div>
            </div>

            <div style="padding: 20px 0px; text-align: center">
                <h1 style="font-size: 30px;">RSVP</h1>
                <div>Will you be attending this event?</div>
            </div>
            <div>
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2" style="text-align: center">
                        <div class="row">
                            <div class="col-sm-4">
                                <a href="" style="border-color:#ec008b" class="btn btn-default">YES</a>
                            </div>
                            <div class="col-sm-4">
                                <a href="" style="border-color:#ec008b" class="btn btn-default">NO</a>
                            </div>
                            <div class="col-sm-4">
                                <a href="" style="border-color:#ec008b" class="btn btn-default">May be</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">&nbsp;</div>
                </div>
            </div>
            <div style="text-align: center; padding: 20px 0px;">
                <h3 style="color:#ec008b">Want to invite a friend?</h3>
                <div>
                    <span style="color:#ec008b">Invite url </span>
                    <span style="border: 1px solid #ccc; padding: 5px;">http://tst.monogramathome.com/event</span>
                </div>
                <div style="text-align: center; padding-top:10px;">
                    <!-- Go to www.addthis.com/dashboard to customize your tools -->
                    <div class="addthis_inline_share_toolbox_u02t"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-59119d559354aa7f"></script>
