<?php $_event = $this->getCurrentEvent(); ?>
<?php $_participate = $this->getCurrentParticipate(); ?>
<?php
$startAt = date_create($_event->getStartAt());
$endAt = date_create($_event->getEndAt());
?>
<div class="col-sm-12">
    <div class="row">
        <div class="col-sm-6">
            <div style="border-style: double; height: 400px; border-color: #ec008b; border-radius: 5px">
                <!-- title -->
                <div style="font-size:24px; padding: 20px; text-align: center">&nbsp;</div>
                <!--  event info -->
                <div style="padding-top: 20px; text-align: center">
                    <h1 style="font-size: 24px; color: #ec008b"><?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>
                        's <?php echo $this->__("Sip and Shop event") ?> </h1>

                    <div>
                        <?php echo $this->__("Please shop until "); ?> <?php echo date_format($endAt, "F/d, Y h:i A"); ?>
                    </div>
                    <div style="padding: 20px 0px; text-align: center">
                        &nbsp;
                    </div>
                    <div style="text-align: center">
                        <a class="btn btn-default" style="background:#ec008b; color: #fff; border: 0 " href="<?php echo Mage::getUrl("party/event/placeOder", array('id' => $_event->getId())) ?>"><?php echo $this->__("SHOP ONLINE NOW >") ?></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <!-- Host message -->
            <div style="background: #eee">
                <div style="padding: 20px 0px; text-align: center">
                    <div style="color:#8b8b8b;">
                        <?php
                        //If applied Yes
                        if ($_participate->getStatus() == 4): ?>
                            I can't wait to see you at this Sip and Shop Event! <br />
                            Great News! If for some reason you are not able to make the event, you can still shop by clicking on "Shop Online Now".   <br/> <br />
                            - <?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>
                        <?php endif ?>
                        <?php
                        //If applied may be
                        if ($_participate->getStatus() == 3): ?>
                            I understand how planning events around a busy lifestyle can be hard! <br /> <br />
                            Thank you for considering to "Shop Online Now" your purchase still counts towards my Host Rewards.
                            <br/>
                            - <?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>
                        <?php endif ?>

                        <?php
                        //If applied No
                        if ($_participate->getStatus() == 2): ?>
                            I know how hard it is to have a conflict and not be able to make this great event.
                            Thank you for considering to "Shop Online Now" <br />
                            Your purchase still counts towards my Host Rewards   <br/> <br />
                            - <?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>
                        <?php endif ?>
                    </div>
                </div>
            </div>

            <div style="padding-top: 5px; text-align: center">
                <h1 style="font-size: 30px;"><?php echo $this->__("RSVP") ?></h1>
            </div>
            <div style="background: #eee">
                <div class="row">
                    <div class="col-sm-12" style="text-align: center; padding-top: 5px;">
                        <?php if ($_participate->getStatus() == 4): ?>
                            <h2 style="font-size: 21px"><?php echo $this->__("Excellent! See you there!"); ?></h2>
                            <h2 style="font-size: 21px"><?php echo $this->__("Yes") ?></h2>
                        <?php elseif ($_participate->getStatus() == 2): ?>
                            <h2 style="font-size: 21px"><?php echo $this->__("Consider hosting an Event of your own!  The Host Reward program is excellent!")?> </h2>
                            <h2 style="font-size: 21px"><?php echo $this->__("NO") ?></h2>
                        <?php elseif ($_participate->getStatus() == 3): ?>
                            <h2 style="font-size: 21px"><?php echo $this->__("We really hope your schedule clears and you can make it!"); ?></h2>
                            <h2 style="font-size: 21px"><?php echo $this->__("May be") ?></h2>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div style="text-align: center; padding: 20px 0px;">
                <div>
                    <div style="color:#ec008b"><?php echo $this->__("Invite url") ?> </div>
                    <div style="border: 1px solid #ccc; padding: 5px;"><?php echo Mage::helper("julfiker_party/event")->getInviteUrl($_event->getId()); ?></div>
                </div>
            </div>
        </div>
    </div>
</div>