<?php
/**
 * Julfiker_Party extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Julfiker
 * @package        Julfiker_Party
 * @copyright      Copyright (c) 2017
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event view template
 *
 * @category    Julfiker
 * @package     Julfiker_Party
 * @author      Ultimate Module Creator
 */
?>
<style>
    .dropdown {
        display: block !important;
    }
</style>
<?php $_event = $this->getCurrentEvent();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$startAt = date_create($_event->getStartAt());
$endAt = date_create($_event->getEndAt());
/** @var \Julfiker_Party_Helper_Event $eventHelper */
$eventHelper = Mage::helper("julfiker_party/event");
?>
<div class="col-md-12">
    <div class="page-title event-title">
        <h1 class="panel-title" >
            <div style="overflow: hidden" >
               <span class="pull-left"><?php echo $this->__("Guest RSVP")?></span>
            </div>
        </h1>
    </div>

    <!-- Event title here -->
    <div class="page-title event-title" style="overflow: hidden">
        <div>
            <span class="pull-left">
               <h3><?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>'s <?php echo $this->__("Event")?></h3>
            </span>
           <span style="color:#ec008b; background: #fff" class="badge pull-right">
               <i class="fa fa-calendar" aria-hidden="true"></i>
               <?php echo date_format($startAt, 'M - d, Y') ?>
           </span>
        </div>
    </div>

    <!-- Event information -->
    <div class="">
        <div class="row">
            <!-- About host -->
            <div class="col-sm-4">
                <b> <i class="fa fa-info-circle" aria-hidden="true"></i> <?php echo $this->__("Host info")?> <br /> </b>
                <div>
                    <?php $host =  Mage::getSingleton('customer/customer')->load($_event->getHost()); ?>
                    <?php echo $this->__("Email:")?> <?php echo $host->getEmail(); ?> <br />
                    <?php echo $this->__("Phone:")?> <?php echo ($host->getPrimaryBillingAddress())?$host->getPrimaryBillingAddress()->getTelephone():""; ?>
                </div>
            </div>
            <!-- Event date and time -->
            <div class="col-sm-5">
                <b><i class="fa fa-calendar" aria-hidden="true" ></i> <?php echo $this->__("Event date and time")?>   </b> <br />
                <div>
                    <?php echo $this->__("Start date")?>: <?php echo date_format($startAt,"M/d,y"); ?> <?php echo $this->__("Start time")?>: <?php echo date_format($startAt,"h:i A"); ?> <br />
                    <?php echo $this->__("End date")?>:  <?php echo date_format($endAt,"M/d,y"); ?> <?php echo $this->__("End time")?>:  <?php echo date_format($endAt,"h:i A"); ?>
                </div>
            </div>
            <!-- Event location or address -->
            <div class="col-sm-3">
                <b> <i class="fa fa-map-marker" aria-hidden="true" ></i> <?php echo $this->__("Event location")?> </b><br />
                <div>
                    <?php echo $_event->getAddress() ?>, <?php echo $_event->getCity() ?> - <?php echo $_event->getZip() ?>, <?php echo $_event->getCountry() ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <hr />
            <?php $invitedUsers = $eventHelper->getInvitedMembers($_event->getId()); ?>
            <div style="padding-top: 20px;">
                <h3><?php echo $this->__("Invited guest")?></h3>
                <!-- Invited guest -->
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th><?php echo $this->__("Name")?></th>
                            <th><?php echo $this->__("Email")?></th>
                            <th><?php echo $this->__("Invited By")?></th>
                            <th><?php echo $this->__("Date")?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (count($invitedUsers)):?>
                        <?php foreach ($invitedUsers as $usr):?>
                            <tr>
                                <td><?php echo $usr['name']?></td>
                                <td><?php echo $usr['email']?></td>
                                <td><?php echo $usr['invitedBy']?></td>
                                <td><?php echo $usr['createdAt']?></td>
                            </tr>
                        <?php endforeach ;?>
                        <?php else: ?>
                            <tr>
                                <td colspan="4">
                                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                                    <?php echo $this->__("No one invited yet!")?></td>
                            </tr>
                        <?php endif ?>
                    </tbody>
                </table>
            </div>

            <?php  $joinedUsers = $eventHelper->getJoinedMembers($_event->getId()); ?>
            <div style="padding-top: 20px;">
                <h3><?php echo $this->__("Joined guest")?></h3>
                <!-- Invited guest -->
                <table class="table table-striped table-hover ">
                    <thead>
                    <tr>
                        <th><?php echo $this->__("Name")?></th>
                        <th><?php echo $this->__("Email")?></th>
                        <th><?php echo $this->__("Date")?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($joinedUsers)):?>
                    <?php foreach ($joinedUsers as $usr):?>
                        <tr>
                            <td><?php echo $usr['name']?></td>
                            <td><?php echo $usr['email']?></td>
                            <td><?php echo $usr['createdAt']?></td>
                        </tr>
                    <?php endforeach ;?>
                    <?php else:?>
                        <tr>
                            <td colspan="3"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                                <?php echo $this->__("No one joined yet!")?></td>
                        </tr>
                    <?php endif ?>
                    </tbody>
                </table>
            </div>

            <?php $interestedUsers = $eventHelper->getInterestedMembers($_event->getId()); ?>
            <?php if (count($interestedUsers)):?>
                <div style="padding-top: 20px;">
                    <h3><?php echo $this->__("Interested guest")?></h3>
                    <!-- Invited guest -->
                    <table class="table table-striped table-hover ">
                        <thead>
                        <tr>
                            <th><?php echo $this->__("Name")?></th>
                            <th><?php echo $this->__("Email")?></th>
                            <th><?php echo $this->__("Date")?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($interestedUsers as $usr):?>
                            <tr>
                                <td><?php echo $usr['name']?></td>
                                <td><?php echo $usr['email']?></td>
                                <td><?php echo $usr['createdAt']?></td>
                            </tr>
                        <?php endforeach ;?>
                        </tbody>
                    </table>
                </div>
            <?php endif ?>

            <?php  $rejectedUsers = $eventHelper->getRejectMembers($_event->getId()); ?>
            <?php if (count($rejectedUsers)):?>
                <div style="padding-top: 20px;">
                    <h3><?php echo $this->__("Event rejected guest")?></h3>
                    <!-- Rejected guest -->
                    <table class="table table-striped table-hover ">
                        <thead>
                        <tr>
                            <th><?php echo $this->__("Name")?></th>
                            <th><?php echo $this->__("Email")?></th>
                            <th><?php echo $this->__("Date")?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php

                        foreach ($rejectedUsers as $usr):?>
                            <tr>
                                <td><?php echo $usr['name']?></td>
                                <td><?php echo $usr['email']?></td>
                                <td><?php echo $usr['createdAt']?></td>
                            </tr>
                        <?php endforeach ;?>
                        </tbody>
                    </table>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>