<?php 
/**
 * Julfiker_Party extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Julfiker
 * @package        Julfiker_Party
 * @copyright      Copyright (c) 2017
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event list template
 *
 * @category    Julfiker
 * @package     Julfiker_Party
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_events = $this->getEvents(); ?>
<div class="page-title event-title">
    <h1><?php echo Mage::helper('julfiker_party')->__('Events') ?></h1>
</div>
<div class="row" style="overflow: hidden; clear: both">
<div class="col-sm-4">
    <div class="control-label" for="search"><?php echo $this->__("Search all events")?></div>
    <div class="input-group">
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
                <i class="fa fa-search" aria-hidden="true" style="color:#ec008b"></i>
            </button>
        </div>
        <input type="text" class="form-control" placeholder="Search by host name" id="txtSearch"/>
    </div>
</div>
<div class="col-sm-8">
    <div class="pull-right">
        <div class="control-label" for="search">&nbsp;</div>
        <a href="<?php echo Mage::getUrl("party/event/create")?>" class="btn btn-default" style="background:#ec008b; color: #fff; border: 0 "><?php echo $this->__("Book an event")?> <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
    </div>
</div>
<?php if ($_events->getSize() > 0): ?>
    <div class="col-sm-12" style="overflow: hidden">
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <div class="col-md-12">
        <div class="panel-group" id="accordion">
            <?php
            $activeClass = "in";
            foreach ($_events as $_event) : ?>
                <?php
                $startAt = date_create($_event->getStartAt());
                $endAt = date_create($_event->getEndAt());
                ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                       <h4 class="panel-title" >
                           <a data-toggle="collapse" data-parent="#accordion"  href="#event_<?php echo $_event->getId()?>">
                               <div style="overflow: hidden" >
                               <span class="pull-left"><i class="fa fa-plus-circle" aria-hidden="true"></i>
                                    <?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>'s <?php echo $this->__("Event")?></span>
                               <span style="color:#ec008b; background: #fff" class="badge pull-right">
                                   <i class="fa fa-calendar" aria-hidden="true"></i>
                                   <?php echo date_format($startAt, 'M d/y') ?>
                               </span>
                               </div>
                           </a>
                       </h4>
                    </div>
                    <div id="event_<?php echo $_event->getId()?>" class="panel-collapse collapse <?php echo $activeClass?>">
                        <div class="panel-body">
                            <?php if ($_event->getDesc()): ?>
                                <p>
                                    <b><i class="fa fa-info-circle"  style="color:#ec008b" aria-hidden="true"></i> <?php echo $this->__("About the event")?> <br /> </b>
                                    <?php echo $_event->getDesc()?>
                                </p>
                            <?php endif ?>

                            <p>
                                <b> <i class="fa fa-location-arrow" aria-hidden="true" style="color:#ec008b"></i> <?php echo $this->__("Event host and location")?> <br /> </b>
                                <?php echo $this->__("Hosted by") ?> <?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?> <br />
                                <?php echo $_event->getAddress() ?>, <?php echo $_event->getCity() ?> - <?php echo $_event->getZip() ?>, <?php echo $_event->getCountry() ?>
                            </p>
                            <p>
                                <b><i class="fa fa-clock-o" aria-hidden="true" style="color:#ec008b"></i> <?php echo $this->__("Event date and time")?>   </b> <br />
                                <b> <?php echo $this->__("Start date")?>:</b> <?php echo date_format($startAt,"M - d, Y"); ?>,  <b><?php echo $this->__("Start time")?> :</b> <?php echo date_format($startAt,"h:i A"); ?> <br />
                                <b> <?php echo $this->__("End date")?>: </b> <?php echo date_format($endAt,"M - d, Y"); ?> ,  <b><?php echo $this->__("End time")?> :</b> <?php echo date_format($endAt,"h:i A"); ?>
                            </p>

                            <hr />
                            <p>
                                <a href="<?php echo $_event->getEventUrl()?>" class="btn btn-default btn-xs"><i class="fa fa-check-circle" aria-hidden="true"></i> More details..</a>
                            </p>
                        </div>
                    </div>
                </div>
            <?php if ($activeClass == "in") $activeClass = ""; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-sm-12" style="overflow: hidden">
        <?php echo $this->getPagerHtml(); ?>
    </div>
<?php else : ?>
    <div class="col-sm-12" style="overflow: hidden">
        <?php echo $this->getPagerHtml(); ?>
    </div>
        <?php echo Mage::helper('julfiker_party')->__('There is no events at this moment');?>
    </div>
<?php endif;?>
</div>
