<?php
/**
 * Julfiker_Party extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Julfiker
 * @package        Julfiker_Party
 * @copyright      Copyright (c) 2017
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event view template
 *
 * @category    Julfiker
 * @package     Julfiker_Party
 * @author      Ultimate Module Creator
 */
?>
<?php $_event = $this->getCurrentEvent();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$startAt = date_create($_event->getStartAt());
$endAt = date_create($_event->getEndAt());
?>
<div class="col-md-12">
    <div class="page-title event-title">
        <h1 class="panel-title" >
            <div style="overflow: hidden" >
               <span class="pull-left"><?php echo $_event->getTitle();?></span>
               <span style="color:#ec008b; background: #fff" class="badge pull-right">
                   <i class="fa fa-calendar" aria-hidden="true"></i>
                   <?php echo date_format($startAt, 'M - d, Y') ?>
               </span>
            </div>
        </h1>
    </div>

    <div style="overflow: hidden">
        <div class="pull-left">
            <a href="<?php echo Mage::getUrl('party/participate/interested')?>?event_id=<?php echo $_event->getId()?>" class="btn btn-default btn-xs"><i class="fa fa-star" aria-hidden="true"></i> Interested</a>
            <a href="#" class="btn btn-default btn-xs" data-backdrop="static" data-keyboard="false"  data-id="<?php echo $_event->getId()?>" data-toggle="modal"  data-target="#going_popup">
                <i class="fa fa-check" aria-hidden="true"></i> Going
            </a>
        </div>
        <div class="pull-right">
            <a href="#" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-id="<?php echo $_event->getId()?>" data-target="#invite_popup" class="btn btn-default btn-xs">
                <i class="fa fa-share-square-o" aria-hidden="true"></i> Invite
            </a>
        </div>
    </div>
    <hr />
    <b>
        <i class="fa fa-pie-chart" aria-hidden="true" style="color:#ec008b"></i>
         <?php echo $this->__("Over view")?>
    </b>
    <div class="row">
        <div class="col-md-3" style="text-align: center">
            <div class="chart" data-percent="0"></div> <!--Todo: calculate percentage -->
            <label><?php echo $this->__("Achieved order")?> <?php echo Mage::helper('core')->currency($this->getTotalOrderAmount(), true, false);?> </label>
        </div>
        <div class="col-md-9" style="padding-top: 20px;">
            <div class="col-md-3" style="text-align: center">
                <div class="chart" data-percent="<?php echo $this->getPercentageJoined() ?>"></div>
                <label>
                    <a href="#" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-member='<?php echo $this->_eventHelper()->getJoinedMembers($_event->getId())?>' data-target="#member_popup">
                    <?php echo $this->__("Joined")?> <?php echo $this->getTotalJoined() ?>
                    </a>
                </label>
            </div>
            <div class="col-md-3" style="text-align: center">
                <div class="chart" data-percent="<?php echo $this->getPercentageInterested() ?>"></div>
                <label>
                    <a href="#" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-member='<?php echo $this->_eventHelper()->getInterestedMembers($_event->getId())?>' data-target="#member_popup">
                        <?php echo $this->__("Interested")?> <?php echo $this->getTotalInterested() ?>
                    </a>
                </label>
            </div>
            <div class="col-md-3" style="text-align: center">
                <div class="chart" data-percent="<?php echo $this->getPercentageInvites()?>"></div>
                <label>
                    <a href="#" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-member='<?php echo $this->_eventHelper()->getInvitedMembers($_event->getId())?>' data-target="#member_popup">
                        <?php echo $this->__("Invited") ?> <?php echo $this->getTotalInvites()?>
                    </a>
                </label>
            </div>
            <div class="col-md-3" style="text-align: center">
                <div class="chart" data-percent="<?php echo $this->getPercentageRejected()?>"></div>
                <label>
                    <a href="#" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-member='<?php echo $this->_eventHelper()->getRejectMembers($_event->getId())?>' data-target="#member_popup">
                        <?php echo $this->__("Rejected") ?> <?php echo $this->getTotalReject()?>
                    </a>
                </label>
            </div>
        </div>
    </div>

    <br />
    <?php if ($_event->getDesc()): ?>
        <p>
            <b><i class="fa fa-info-circle"  style="color:#ec008b" aria-hidden="true"></i> <?php echo $this->__("About the event")?> <br /> </b>
            <?php echo $_event->getDesc()?>
        </p>
    <?php endif ?>

    <p>
        <b> <i class="fa fa-location-arrow" aria-hidden="true" style="color:#ec008b"></i> <?php echo $this->__("Event host and location")?> <br /> </b>
        <?php echo $this->__("Hosted by") ?> <?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?> <br />
        <?php echo $_event->getAddress() ?>, <?php echo $_event->getCity() ?> - <?php echo $_event->getZip() ?>, <?php echo $_event->getCountry() ?>
    </p>

    <p>
        <b><i class="fa fa-clock-o" aria-hidden="true" style="color:#ec008b"></i> <?php echo $this->__("Event date and time")?>   </b> <br />
        <b> <?php echo $this->__("Start date")?>:</b> <?php echo date_format($startAt,"M - d, Y"); ?>,  <b><?php echo $this->__("Start time")?> :</b> <?php echo date_format($startAt,"h:i A"); ?> <br />
        <b> <?php echo $this->__("End date")?>: </b> <?php echo date_format($endAt,"M - d, Y"); ?> ,  <b><?php echo $this->__("End time")?> :</b> <?php echo date_format($endAt,"h:i A"); ?>
    </p>
</div>


<div  class="col-md-12" style="padding-top: 20px;">
    <?php
        if(Mage::getSingleton('customer/session')->isLoggedIn())
            $customerId = Mage::getSingleton('customer/session')->getId();
    ?>
    <b><?php echo $this->__("Invite Url")?></b>
    <div style="border: 1px solid #eee; padding: 10px 5px;"><?php echo $_event->getEventUrl()."?refer=".base64_encode($customerId) ?></div>
</div>

<script>
    jQuery(document).ready(function() {
        jQuery('.chart').circliful({
            animate : true,
            diameter : 5000,
            guage: 2,
            coverBg: '#fff',
            bgColor: '#fff',
            fillColor: '#fff',
            foregroundColor: "#ec008b",
            percentSize: '15px',
            percentWeight: 'bold'
        });
    });

</script>


<div class="modal fade" id="invite_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->__('Invite peoples to join') ?></h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo Mage::getUrl('party/participate/invite')?>" method="post">
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">Member</label>
                        <?php $customers = $this->getCustomers(); ?>
                        <select class="form-control" name="members" multiple>
                            <?php foreach ($customers as $cstmr):?>
                                <?php $customer = Mage::getModel("customer/customer")->load($cstmr->getId());?>
                                <option value="<?php echo $customer->getEmail()?>"><?php echo $customer->getName()?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">Input email</label>
                        <input class="form-control" id="inputDefault" name="emails[1]" type="text">
                        <!--span class="help-block">Please provide comma(,) separate email address. And invitation will be notified through email.</span-->
                        <input type="hidden" value=""  id="event_id" name="event_id" />
                        <input type="hidden" value=""  id="id" name="id" />
                    </div>
                    <div class="form-group">
                        <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
                        <button style="margin-left: 5px" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Send')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="member_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <ul class="list-group">
                    <li class="list-group-item">First item</li>
                    <li class="list-group-item">Second item</li>
                    <li class="list-group-item">Third item</li>
                </ul>
                <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="going_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->__('Join in event') ?></h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo Mage::getUrl('party/participate/going')?>" method="post">
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">No. of Guest</label>
                        <input class="form-control" id="inputDefault" name="guest" type="text">
                        <!--span class="help-block">Please provide comma(,) separate email address. And invitation will be notified through email.</span-->
                        <input type="hidden" value="" class="event_id"  id="event_id" name="event_id" />
                        <input type="hidden" value=""  id="id" name="id" />
                    </div>
                    <div class="form-group">
                        <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
                        <button style="margin-left: 5px" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Join')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function() {
        jQuery('#invite_popup').on("show.bs.modal", function (e) {
            var id = jQuery(e.relatedTarget).data('id');
            jQuery(document).find("#event_id").val(id);
        });
        jQuery('#going_popup').on("show.bs.modal", function (e) {
            var id = jQuery(e.relatedTarget).data('id');
            jQuery(document).find(".event_id").val(id);
        });
        jQuery('#member_popup').on("show.bs.modal", function (e) {
            var members = jQuery(e.relatedTarget).data('member');
            var list = jQuery(this).find('.list-group').html("");
            jQuery.each(members, function(key,value){
                list.append('<li class="list-group-item">'+value.name+' ('+value.email+')</li>');
            });
        });
    })
</script>