<?php
/**
 * Julfiker_Party extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Julfiker
 * @package        Julfiker_Party
 * @copyright      Copyright (c) 2017
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event view template
 *
 * @category    Julfiker
 * @package     Julfiker_Party
 * @author      Ultimate Module Creator
 */
?>
<style>
    .dropdown {
        display: block !important;
    }
</style>
<?php $_event = $this->getCurrentEvent();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$startAt = date_create($_event->getStartAt());
$endAt = date_create($_event->getEndAt());
?>
<div class="col-md-12">
    <div class="page-title event-title">
        <h1 class="panel-title" >
            <div style="overflow: hidden" >
               <span class="pull-left"><?php echo $this->__("Event")?></span>
            </div>
        </h1>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <div class="control-label" for="search"><?php echo $this->__("Search all events")?></div>
            <div class="input-group">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="fa fa-search" aria-hidden="true" style="color:#ec008b"></i>
                    </button>
                </div>
                <input type="text" class="form-control" placeholder="Search by host name" id="txtSearch"/>
            </div>
        </div>
        <div class="col-xs-8">
            <div class="pull-right">
                <div class="control-label" for="search">&nbsp;</div>
                <a href="<?php echo Mage::getUrl("party/event/create")?>" class="btn btn-default" style="background:#ec008b; color: #fff; border: 0 "><?php echo $this->__("Book an event")?> <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    </div>
    <hr />

    <!-- Event title here -->
    <div class="page-title event-title" style="overflow: hidden">
        <div>
            <span class="pull-left">
               <h3><?php echo Mage::helper("julfiker_party/event")->getHostName($_event->getHost()); ?>'s <?php echo $this->__("Event")?></h3>
            </span>
           <span style="color:#ec008b; background: #fff" class="badge pull-right">
               <i class="fa fa-calendar" aria-hidden="true"></i>
               <?php echo date_format($startAt, 'M - d, Y') ?>
           </span>
        </div>
    </div>

    <!-- Event information -->
    <div class="col-md-12">
        <div class="row">
            <!-- About host -->
            <div class="col-sm-3">
                <b> <i class="fa fa-info-circle" aria-hidden="true"></i> <?php echo $this->__("Host info")?> <br /> </b>
                <div>
                    <?php $host =  Mage::getSingleton('customer/customer')->load($_event->getHost()); ?>
                    <?php echo $host->getEmail(); ?> <br />
                    <?php echo ($host->getPrimaryBillingAddress())?$host->getPrimaryBillingAddress()->getTelephone():""; ?>
                </div>
            </div>
            <!-- Event date and time -->
            <div class="col-sm-5">
                <b><i class="fa fa-calendar" aria-hidden="true" ></i> <?php echo $this->__("Event date and time")?>   </b> <br />
                <div>
                    <?php echo $this->__("Start date")?>: <?php echo date_format($startAt,"M/d,y"); ?> <?php echo $this->__("Start time")?>: <?php echo date_format($startAt,"h:i A"); ?> <br />
                    <?php echo $this->__("End date")?>:  <?php echo date_format($endAt,"M/d,y"); ?> <?php echo $this->__("End time")?>:  <?php echo date_format($endAt,"h:i A"); ?>
                </div>
            </div>
            <!-- Event location or address -->
            <div class="col-sm-4">
                <b> <i class="fa fa-map-marker" aria-hidden="true" ></i> <?php echo $this->__("Event location")?> </b><br />
                <div>
                    <?php echo $_event->getAddress() ?>, <?php echo $_event->getCity() ?> - <?php echo $_event->getZip() ?>, <?php echo $_event->getCountry() ?>
                </div>
            </div>
        </div>
    </div>

    <?php if (Mage::helper("julfiker_party/event")->checkEventPermission()):?>
    <!-- circle graph -->
    <div class="col-md-12" style="padding-top: 10px;">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <!-- Invite circle -->
                    <div class="col-md-4" style="text-align: center">
                        <div id="circle-invited" class="circle"
                             data-dimension="250"
                             data-text="Invited"
                             data-width="30"
                             data-percent="<?php echo $this->getPercentageInvites() ?>"
                             data-fgcolor="#61a9dc"
                             data-bgcolor="#eee"
                             data-fill="#000"
                             data-total="40"
                             data-noPercentageSign="true"
                             data-replacePercentageByText="<?php echo $this->getTotalInvites() ?>"
                             data-description="test"
                             data-foregroundColor="#ec008b"
                             data-textStyle="font-size:14px;"
                             data-textColor="#000"
                             data-animateInView="true"
                             data-fontColor="#000"
                             data-part="20"></div>
                        <label>
                            <a href="#" data-backdrop="static" data-keyboard="false" data-toggle="modal"
                               data-title="Invited"
                               data-member='<?php echo $this->_eventHelper()->getInvitedMembers($_event->getId()) ?>'
                               data-target="#member_popup">
                                <?php echo $this->__("Goal invites 40+") ?>
                            </a>
                        </label>
                    </div>
                    <!-- Joined circle -->
                    <div class="col-md-4" style="text-align: center">
                        <div id="circle-attending" class="circle"
                             data-dimension="250"
                             data-text="Attending"
                             data-width="30"
                             data-percent="<?php echo $this->getPercentageJoined() ?>"
                             data-fgcolor="#61a9dc"
                             data-bgcolor="#eee"
                             data-fill="#000"
                             data-total="40"
                             data-noPercentageSign="true"
                             data-replacePercentageByText="<?php echo $this->getTotalJoined() ?>"
                             data-description="test"
                             data-foregroundColor="#ec008b"
                             data-textStyle="font-size:14px;"
                             data-textColor="#000"
                             data-animateInView="true"
                             data-fontColor="#000"
                             data-part="20"></div>
                        <label>
                            <a href="#" data-backdrop="static" data-keyboard="false" data-toggle="modal"
                               data-title="Joined"
                               data-member='<?php echo $this->_eventHelper()->getJoinedMembers($_event->getId()) ?>'
                               data-target="#member_popup">
                                <?php echo $this->__("Goal 10 attending") ?>
                            </a>
                        </label>
                    </div>
                    <!-- Order circle -->
                    <div class="col-md-4" style="text-align: center">
                        <div id="circle-order" class="circle"
                             data-dimension="250"
                             data-text="Order"
                             data-width="30"
                             data-percent="<?php echo $this->getPercentageTotalOrders() ?>"
                             data-fgcolor="#61a9dc"
                             data-bgcolor="#eee"
                             data-fill="#000"
                             data-total="40"
                             data-noPercentageSign="true"
                             data-replacePercentageByText="<?php echo $this->getTotalOrders() ?>"
                             data-description="test"
                             data-foregroundColor="#ec008b"
                             data-textStyle="font-size:14px;"
                             data-textColor="#000"
                             data-animateInView="true"
                             data-fontColor="#000"
                             data-part="20"></div>
                        <label><?php echo $this->__("Goal 13 order") ?> </label>
                    </div>
                </div>
            </div>

            <div class="col-md-4" style="border-left: 1px solid #eee">
                <div class="row" style="padding: 10px 10px;">
                    <div>
                        <h3><?php echo $this->__("Cash Earnings"); ?></h3>
                        <span><?php echo Mage::helper('core')->currency($this->getTotalOrderAmount(), true, false); ?></span>
                    </div>
                    <div style="padding-top: 10px;">
                        <h3><?php echo $this->__("Retail Sales"); ?></h3>
                        <span>$0</span>
                    </div>
                    <div style="padding-top: 10px;">
                        <h3><?php echo $this->__("Host Rewards"); ?></h3>
                        <span>$0</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif ?>

</div>


<div  class="col-md-12" style="padding-top: 20px;">
    <?php
        if(Mage::getSingleton('customer/session')->isLoggedIn())
            $customerId = Mage::getSingleton('customer/session')->getId();
    ?>
    <b><?php echo $this->__("Invite Url")?></b>
    <div style="border: 1px solid #eee; padding: 10px 5px;"><?php echo $_event->getEventUrl()."?refer=".base64_encode($customerId) ?></div>
</div>

<div class="col-md-12" style="padding-top: 20px;">
    <div class="row">
        <div class="col-xs-6">
            <a href="#" class="btn btn-default"><?php echo $this->__("Manage Guest") ?></a>
            <a href="#" class="btn btn-default"><?php echo $this->__("View Guest List") ?></a>
        </div>
        <div class="col-xs-6">
            <div class="dropdown pull-right">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><?php echo $this->__("Action")?>
                    <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="<?php echo Mage::getUrl("party/participate/confirm", array("_query"=>array('event_id' => $_event->getId())))?>">
                            <?php echo $this->__("Join this event");?>
                        </a>
                    </li>
                    <li>
                        <a href="#" href="#"
                           data-backdrop="static"
                           data-keyboard="false"
                           data-toggle="modal"
                           data-id="<?php echo $_event->getId()?>"
                           data-target="#invite_popup" ><?php echo $this->__("Personalize Invitation");?></a>
                    </li>
                    <li><a href="#"
                           data-backdrop="static"
                           data-keyboard="false"
                           data-toggle="modal"
                           data-id="<?php echo $_event->getId()?>"
                           data-target="#invite_popup"><?php echo $this->__("Invite guests")?></a></li>
                    <li>
                        <a href="#">
                            <?php echo $this->__("View Guest RSVPs");?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl("party/event/placeOder", array('id' => $_event->getId()))?>">
                            <?php echo $this->__("Place an order");?>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <?php echo $this->__("Edit event");?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl("party/event/delete", array('id' => $_event->getId()))?>" onclick="return confirm('Want to delete?')">
                            <?php echo $this->__("Delete event");?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    jQuery(document).ready(function() {
      jQuery('#circle-invited').circliful();
      jQuery('#circle-attending').circliful();
      jQuery('#circle-order').circliful();
    });
</script>

<div class="modal fade" id="invite_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->__('Invite peoples to join') ?></h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo Mage::getUrl('party/participate/invite')?>" method="post">
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">Member</label>
                        <?php $contacts = $this->getContacts(); ?>
                        <select class="form-control" name="members[]" multiple>
                            <?php foreach ($contacts as $contact):?>
                                <option value="<?php echo $contact->getId()?>"><?php echo $contact->getFirstName()?> <?php echo $contact->getLastName()?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">Input email</label>
                        <input class="form-control" id="inputDefault" name="emails[0]" type="text">
                        <!--span class="help-block">Please provide comma(,) separate email address. And invitation will be notified through email.</span-->
                        <input type="hidden" value=""  id="event_id" name="event_id" />
                        <input type="hidden" value=""  id="id" name="id" />
                    </div>
                    <div class="form-group">
                        <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
                        <button style="margin-left: 5px" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Send')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="member_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <ul class="list-group">
                </ul>
                <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="going_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->__('Join in event') ?></h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo Mage::getUrl('party/participate/going')?>" method="post">
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">No. of Guest</label>
                        <input class="form-control" id="inputDefault" name="guest" type="text">
                        <!--span class="help-block">Please provide comma(,) separate email address. And invitation will be notified through email.</span-->
                        <input type="hidden" value="" class="event_id"  id="event_id" name="event_id" />
                        <input type="hidden" value=""  id="id" name="id" />
                    </div>
                    <div class="form-group">
                        <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
                        <button style="margin-left: 5px" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Join')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function() {
        jQuery('#invite_popup').on("show.bs.modal", function (e) {
            var id = jQuery(e.relatedTarget).data('id');
            jQuery(document).find("#event_id").val(id);
        });
        jQuery('#going_popup').on("show.bs.modal", function (e) {
            var id = jQuery(e.relatedTarget).data('id');
            jQuery(document).find(".event_id").val(id);
        });
        jQuery('#member_popup').on("show.bs.modal", function (e) {
            var title = jQuery(e.relatedTarget).data('title');
            jQuery(this).find('.modal-title').text(title);
            var members = jQuery(e.relatedTarget).data('member');

            var list = jQuery(this).find('.list-group').html("");
            jQuery.each(members, function(key,value){
                list.append('<li class="list-group-item">'+value.name+' ('+value.email+')<br /> <span class="small">Invited by '+value.invitedBy+' &nbsp; at '+value.createdAt+'</span></li>');
            });
        });
    })
</script>

<?php if(false):?>
    <div style="overflow: hidden">
        <div class="pull-left">
            <a href="<?php echo Mage::getUrl('party/participate/interested')?>?event_id=<?php echo $_event->getId()?>" class="btn btn-default btn-xs"><i class="fa fa-star" aria-hidden="true"></i> Interested</a>
            <a href="#" class="btn btn-default btn-xs" data-backdrop="static" data-keyboard="false"  data-id="<?php echo $_event->getId()?>" data-toggle="modal"  data-target="#going_popup">
                <i class="fa fa-check" aria-hidden="true"></i> Going
            </a>
        </div>
        <div class="pull-right">
            <a href="#" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-id="<?php echo $_event->getId()?>" data-target="#invite_popup" class="btn btn-default btn-xs">
                <i class="fa fa-share-square-o" aria-hidden="true"></i> Invite
            </a>
        </div>
    </div>
<?php endif ?>