
<div class="modal fade" id="location_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->__('Add new address') ?></h4>
            </div>
            <div class="modal-body">
                <div class="account-create">
                    <?php //echo $this->getChildHtml('form_fields_before')?>
                    <?php //echo $this->getChildHtml('customer.form.register.extra')?>
                    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
                        <?php if($this->getShowAddressFields() or true): ?>
                            <div class="fieldset">
                                <input type="hidden" name="create_address" value="1" />
                                <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                                <ul class="form-list">
                                    <li class="fields">
                                        <div class="field">
                                            <label for="company"><?php echo $this->__('Company') ?></label>
                                            <div class="input-box">
                                                <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                            <div class="input-box">
                                                <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                                            </div>
                                        </div>
                                    </li>
                                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                                    <li class="wide">
                                        <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                                        <div class="input-box">
                                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                                        </div>
                                    </li>
                                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                        <li class="wide">
                                            <div class="input-box">
                                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                            </div>
                                        </li>
                                    <?php endfor; ?>
                                    <li class="fields">
                                        <div class="field">
                                            <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                            <div class="input-box">
                                                <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State / Province') ?></label>
                                            <div class="input-box">
                                                <select id="region_id1" name="region_id" title="<?php echo $this->__('State / Province') ?>" class="validate-select" style="display:none;">
                                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                                </select>
                                                <script type="text/javascript">
                                                    //<![CDATA[
                                                    $('region_id1').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                                    //]]>
                                                </script>
                                                <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State / Province') ?>" class="input-text" style="display:none;" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="fields">
                                        <div class="field">
                                            <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                            <div class="input-box">
                                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                            <div class="input-box">
                                                <?php echo $this->getCountryHtmlSelect() ?>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                                <input type="hidden" name="default_billing" value="1" />
                                <input type="hidden" name="default_shipping" value="1" />
                            </div>
                        <?php endif; ?>
                        <div class="buttons-set">
                            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                            <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
                            <button style="margin-left: 5px" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                        </div>
                    </form>
                    <script type="text/javascript">
                        //<![CDATA[
                        var dataForm = new VarienForm('form-validate', true);
                        <?php if($this->getShowAddressFields() or true): ?>
                        new RegionUpdater('country', 'region', 'region_id1', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
                        <?php endif; ?>
                        //]]>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>