<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title event-title">
    <h1><?php echo Mage::helper('julfiker_party')->__('Add new contact') ?></h1>
</div>
<div class="row" style="overflow: hidden; clear: both">
    <div class="col-sm-12">
        <div class="account-create">
            <?php echo $this->getChildHtml('form_fields_before') ?>
            <?php echo $this->getChildHtml('customer.form.register.extra') ?>
            <form action="<?php echo Mage::getUrl("julfiker_party/contact/createpost") ?>" method="post"
                  id="form-member">
                <div class="fieldset">
                    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>"/>
                    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>"/>

                    <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
                    <ul class="form-list">
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                        </li>
                        <li>
                            <label for="email_address"
                                   class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                            <div class="input-box">
                                <input type="text" name="email" id="email_address"
                                       value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
                                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>"
                                       class="input-text validate-email required-entry"/>
                            </div>
                        </li>
                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                        <?php endif ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                        <?php endif ?>
                    </ul>
                </div>
                <?php if ($this->getShowAddressFields() or true): ?>
                    <div class="fieldset">
                        <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                        <ul class="form-list">
                            <li class="fields">
                                <div class="field">
                                    <label for="telephone"
                                           class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                                    <div class="input-box">
                                        <input type="text" name="telephone" id="telephone"
                                               value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>"
                                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>"
                                               class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"/>
                                    </div>
                                </div>
                            </li>
                            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                            <li class="wide">
                                <label for="street_1"
                                       class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>

                                <div class="input-box">
                                    <input type="text" name="street"
                                           value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>"
                                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
                                           id="street_1" class="input-text <?php echo $_streetValidationClass ?>"/>
                                </div>
                            </li>
                            <li class="fields">
                                <div class="field">
                                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>

                                    <div class="input-box">
                                        <input type="text" name="city"
                                               value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>"
                                               title="<?php echo $this->__('City') ?>" class="input-text required-entry"
                                               id="city"/>
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="region_id"
                                           class="required"><em>*</em><?php echo $this->__('State / Province') ?>
                                    </label>

                                    <div class="input-box">
                                        <select id="region_id" name="region_id"
                                                title="<?php echo $this->__('State / Province') ?>"
                                                class="validate-select" style="display:none;">
                                            <option
                                                value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                        </select>
                                        <script type="text/javascript">
                                            //<![CDATA[
                                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                            //]]>
                                        </script>
                                        <input type="text" id="region" name="region"
                                               value="<?php echo $this->htmlEscape($this->getRegion()) ?>"
                                               title="<?php echo $this->__('State / Province') ?>" class="input-text"
                                               style="display:none;"/>
                                    </div>
                                </div>
                            </li>
                            <li class="fields">
                                <div class="field">
                                    <label for="zip"
                                           class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                                    <div class="input-box">
                                        <input type="text" name="postcode"
                                               value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>"
                                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>"
                                               id="zip"
                                               class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"/>
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?>
                                    </label>

                                    <div class="input-box">
                                        <?php echo $this->getCountryHtmlSelect() ?>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('Customer Interests') ?></h2>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="form-group">
                                <div style="display: block">Email Sign up</div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="interest_in_news_letter_corporate_email" name="newsletter[]"> <?php echo $this->__("This customer wishes to receive monogram @ home corporate marketing email")?>
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="interest_in_hosting_event" name="newsletter[]"> <?php echo $this->__("Hosting a sip and shop event")?>
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="interest_in_becoming_ambassador" name="newsletter[]"> <?php echo $this->__("Become an ambassador")?>
                                    </label>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('Notes') ?></h2>
                    <ul class="form-list">
                        <li class="fields">
                            <div class="form-group">
                                <textarea class="form-control" rows="2" style="height: auto" name="note"></textarea>
                                <span class="help-block"><?php echo $this->__("250 characters")?></span>
                            </div>
                        </li>
                    </ul>
                </div>

                <?php endif; ?>

                <div class="buttons-set">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button style="margin-left: 5px" type="submit"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button">
                        <span><span><?php echo $this->__('Submit') ?></span></span></button>
                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var dataForm = new VarienForm('form-member', true);
                <?php if($this->getShowAddressFields() or true): ?>
                new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
                <?php endif; ?>
                //]]>
            </script>
        </div>
    </div>
</div>
