<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
    $_event = ($this->getEvent())?$this->getEvent():Mage::getModel('julfiker/party');
    $isSelfHost = false;
    if ($_event)
    $isSelfHost = $this->isHostAsMyself($_event->getHost());
?>
<form class="form-horizontal" action="<?php echo $this->getSavingAction()?><?php if ($_event):?>id/<?php echo $_event->getId()?><?php endif ?>" method="post" id="event_form">
    <fieldset>
        <legend style="display: block"><?php echo $this->__("Book an event")?></legend>
        <div class="col-sm-10">
            <div class="form-group">
                <label for="desc" class="control-label">Event detail</label>
                <textarea class="form-control" name="event[desc]" rows="3" id="desc"><?php echo ($_event)? $_event->getDesc():"";  ?></textarea>
                <span class="help-block"><?php echo $this->__("Some information about the event")?></span>
            </div>
            <div class="form-group">
                <label class="control-label"><?php echo $this->__("Host Information")?></label>
                <div class="radio">
                    <label>
                        <input name="event[host]" id="optionsRadios1" class="customer_host" value="member"  checked="" type="radio">
                        <?php echo $this->__("A customer is hosting this event") ?>
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input name="event[host]" id="optionsRadios2" class="self_host" value="self"  <?php if ($isSelfHost == true):?> checked="checked" <?php endif ?> type="radio">
                        <?php echo $this->__("I am hosting this event")?>
                    </label>
                </div>
            </div>
            <div class="form-group" id="customer_block" <?php if ($isSelfHost == true):?> style="display: none" <?php endif ?>>
                <label for="inputTitle" class="control-label"><?php echo $this->__("Choose member")?></label>
                <div style="overflow: hidden">
                    <div class="col-md-8" style="padding-left: 0">
                        <select class="form-control required-entry" name="event[member]" id="customers">
                            <option value=""><?php echo $this->__("Select member")?></option>
                            <?php foreach($this->getCustomers() as $customer):?>
                                <option value="<?php echo $customer->getId()?>" <?php if ($_event && $customer->getId()==$_event->getHost()):?> selected="selected" <?php endif ?>><?php echo $customer->getName()?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="col-md-4" style="padding-left:0;"> OR &nbsp;<a href="#new_customer" data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-target="#customer_popup" class="btn btn-default"><?php echo $this->__("Add new member")?></a></div>
                </div>
            </div>
            <div class="form-group">
                <div class="event_tab">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" id="person_trigger" href="#person_event"><?php echo $this->__("In-person Event")?></a></li>
                        <li><a data-toggle="tab" id="online_trigger" href="#online_event"><?php echo $this->__("Online event")?></a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div id="person_event" class="tab-pane fade in active">
                        <div class="">
                            <label class="control-label"><?php echo $this->__("Event location")?></label>
                            <div class="radio">
                                <label>
                                    <input name="event[loc_type]" class="host_loc" value="default" checked="" type="radio">
                                    <?php echo $this->__("Host default address.")?>
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input name="event[loc_type]" class="diff_loc" value="diff" type="radio">
                                    <?php echo $this->__("Different Location")?>
                                </label>
                            </div>
                        </div>
                        <div class="" id="address_block" style="display: none">
                        <label class="control-label"><?php echo $this->__("Choose location")?></label>
                        <div style="overflow: hidden">
                            <div class="col-md-8" style="padding-left: 0">
                                <select class="form-control required-entry" id="addresses" name="event[addressId]">
                                    <option value=""><?php echo $this->__("Address")?></option>
                                </select>
                            </div>
                            <div class="col-md-4" style="padding-left:0;"> OR &nbsp; <a href="#" class="btn btn-default"  data-backdrop="static" data-keyboard="false"  data-toggle="modal" data-target="#location_popup" ><?php echo $this->__("Add new location")?></a></div>
                        </div>
                    </div>
                    </div>
                    <div id="online_event" class="tab-pane fade out">
                        <p>&nbsp;
                            <input type="hidden" id="is_online" name="event[is_online]" value="0" />
                        </p>
                    </div>
                </div>
            </div>

            <?php
               if ($_event) {
                   $startAt = date_create($_event->getStartAt());
                   $endAt = date_create($_event->getEndAt());
               }
            ?>

            <div class="form-group">
                <label class="control-label">
                    <?php echo $this->__("Start from at")?>
                </label>
                <div style="overflow: hidden">
                    <div class="col-xs-7" style="padding-left:0;">
                        <input type='text' readonly="readonly" <?php if ($startAt):?> value=" <?php echo date_format($startAt, 'm/d/Y') ?>" <?php endif ?> class="form-control required-entry validate-date-range validate-date date-range-custom_theme-from" id="start_at" name="event[start_at]"
                               style="float: left; width: 90%; cursor: pointer;  background-color: #fff;" />
                        <img title="Select date" id="_start_at" src="<?php echo $this->getSkinUrl('images/calendar.gif')?>" class="v-middle" style="float: left; padding-top: 10px">
                    </div>
                    <div class="col-xs-2" style="padding-left:0;">
                        <select class="timeSelect1 form-control start_time" name="event[start_time]" <?php if (isset($startAt) && $startAt):?> data-time="<?php echo date_format($startAt, 'h:i A') ?>" <?php endif ?>>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">
                    <?php echo $this->__("End to at")?>
                </label>
                <div style="overflow: hidden">
                    <div class="col-xs-7" style="padding-left:0; overflow: hidden">
                        <input type='text'  readonly="readonly" <?php if (isset($endAt) && $endAt):?> value=" <?php echo date_format($endAt, 'm/d/Y') ?>" <?php endif ?> class="form-control required-entry validate-date-range validate-date date-range-custom_theme-to" id="end_at" name="event[end_at]"
                               style="float: left; width: 90%; cursor: pointer;  background-color: #fff;" />
                        <img title="Select date" id="_end_at" src="<?php echo $this->getSkinUrl('images/calendar.gif')?>" class="v-middle" style="float: left; padding-top: 10px">
                    </div>
                    <div class="col-xs-2" style="padding-left:0;">
                        <select class="timeSelect2 end_time form-control" id="end_time"  name="event[end_time]" <?php if (isset($endAt) && $endAt):?> data-time="<?php echo date_format($endAt, 'h:i A') ?>" <?php endif ?>>
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="">
                    <button class="button pink-button" title="Cancel"  type="reset">
                        <span>
                            <span><?php echo $this->__("Reset")?></span>
                        </span>
                    </button>
                    <button class="button pink-button" title="Book NOW"  type="submit">
                        <span>
                            <?php if ($_event):?>
                            <span><?php echo $this->__("Save")?></span>
                            <?php else: ?>
                                <span><?php echo $this->__("Book Now")?></span>
                            <?php endif ?>
                        </span>
                    </button>
                </div>
            </div>
        </div>
    </fieldset>
</form>

<script>
    jQuery(document).ready(function(){
        Calendar.setup({
            inputField : 'start_at',
            ifFormat : '%m/%e/%Y',
            button : '_start_at',
            align : 'Bl',
            singleClick : true,
            disableFunc: function(date) {
                var now= new Date();
                if(date.getFullYear()<now.getFullYear())
                {
                    return true;
                }
                if(date.getFullYear()==now.getFullYear())
                {
                    if(date.getMonth()<now.getMonth())
                    {
                        return true;
                    }
                }
                if(date.getMonth()==now.getMonth())
                {
                    if(date.getDate()<now.getDate())
                    {
                        return true;
                    }
                }
            },
        });

        Calendar.setup({
            inputField : 'end_at',
            ifFormat : '%m/%e/%Y',
            button : '_end_at',
            align : 'Bl',
            singleClick : true,
            disableFunc: function(date) {
                var now= new Date();
                if(date.getFullYear()<now.getFullYear())
                {
                    return true;
                }
                if(date.getFullYear()==now.getFullYear())
                {
                    if(date.getMonth()<now.getMonth())
                    {
                        return true;
                    }
                }
                if(date.getMonth()==now.getMonth())
                {
                    if(date.getDate()<now.getDate())
                    {
                        return true;
                    }
                }
            },
        });

        jQuery('#online_trigger').click(function() {
            jQuery(document).find("#is_online").val(1);
        });

        jQuery('#person_trigger').click(function() {
            jQuery(document).find("#is_online").val(0);
        })
    });
</script>