<div class="modal fade" id="invite_popup">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->__('Invite peoples to join') ?></h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo $this->getInviteAction()?>?event_id=<?php echo $_GET['event_id']?>">
                    <div class="form-group">
                        <label class="control-label" for="inputDefault">Input email</label>
                        <input class="form-control" id="inputDefault" type="text">
                        <span class="help-block">Please provide comma(,) separate email address. And invitation will be notified through email.</span>
                    </div>
                    <div class="form-group">
                        <button type="button" data-dismiss="modal" aria-hidden="true" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close window')) ?>" class="button"><span><span><?php echo $this->__('Close') ?></span></span></button> &nbsp;
                        <button style="margin-left: 5px" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Send')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
